### ISSUE TITLE
you can warn ops

### ISSUE THREAD

**Issue by dries-c** [MCrafterss/WarnPlayer#1]

**Comment by MiroTheSuperDev** [comment]
i am still thinking how to fix that

**Comment by dries-c** [comment]
i think if $player != isOP

**Comment by LittleBigMC** [comment]
If ($player->isOp){
$event->setCancelled()
}

**Comment by OneebAamer** [comment]
Its if($player->isOp()){

**Comment by dries-c** [comment]
oops sorry

**Comment by MiroTheSuperDev** [comment]
i know but it is a command not a event

**Comment by OneebAamer** [comment]
Hmm maybe do return true;

**Comment by MiroTheSuperDev** [comment]
also sometimes pureperms overide op permissions

**Comment by OneebAamer** [comment]
If($player->isOp()){
Return true;
}

**Comment by OneebAamer** [comment]
If($player->hasPermission())???

**Comment by MiroTheSuperDev** [comment]
i think it should be

if($this->player->hasPermission('warnplayer.bypass'){

**Comment by MiroTheSuperDev** [comment]
i was just typing it

**Comment by MiroTheSuperDev** [comment]
your too fast oneeb

**Comment by MiroTheSuperDev** [comment]
but how would we prevent the command from bieng executed  on the player

**Comment by OneebAamer** [comment]
Lol umm idk

**Comment by OneebAamer** [comment]
If($cmd->getName() === "warn"){
If($args[0] instanceof Player){
If($arg[0]->getPlayer()->isOp()){
Return true;
}
}
}
MAYBE not sure though

**Comment by MiroTheSuperDev** [comment]
ok good idea you commit it then i will add support if pureperms is added

then were done

**Comment by OneebAamer** [comment]
Ok

**Comment by OneebAamer** [comment]
Wait can u do it im a little busy rn cya in a bit.

**Comment by applqpak** [comment]
You should be able to warn OPs.

**Comment by AmiroEmad** [comment]
but ops can warn the owner

then i have an idea to disable warning the owner

**Comment by MiroTheSuperDev** [comment]
@applqpak but i think we shouldn't be able to warn server owner lol

**Comment by MiroTheSuperDev** [comment]
If($cmd->getName() === "warn" and !($this-getConfig("server-owner-name") == $args[0])){
If($args[0] instanceof Player){

would this work right ??

**Comment by MiroTheSuperDev** [comment]
then after that we put sender send message you cant warn the server owner

**Comment by xBeastMode** [comment]
Guys save warns in SQLite.

**Comment by MiroTheSuperDev** [comment]
@xBeastMode not all mcpe servers have their own database

**Comment by xBeastMode** [comment]
Yes, all softwares forked from pocketmine have SQLite database, idk about nukkit though since it's all in java.

**Comment by MiroTheSuperDev** [comment]
@xBeastMode but not all vps offer sql plan and if people host it on there pc not all pc have sql installed

**Comment by xBeastMode** [comment]
Not SQL, SQLite. It's a database that is saved on a ".db". An SQLite database doesn't need username, password, etc.

**Comment by MiroTheSuperDev** [comment]
thx for telling me that
